from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from .models import User,News,Infographic,Publication,Data, HumanDevelopmentIndex, HotelOccupancyCombined, HotelOccupancyYearly, GiniRatio, IPM_UHH_SP, IPM_HLS, IPM_RLS, IPM_PengeluaranPerKapita, IPM_IndeksKesehatan, IPM_IndeksHidupLayak, IPM_IndeksPendidikan, KetenagakerjaanTPT, KetenagakerjaanTPAK, KemiskinanSurabaya, KemiskinanJawaTimur, Kependudukan, PDRBPengeluaranADHB, PDRBPengeluaranADHK, PDRBPengeluaranDistribusi, PDRBPengeluaranLajuPDRB, PDRBPengeluaranADHBTriwulanan, PDRBPengeluaranADHKTriwulanan, PDRBPengeluaranDistribusiTriwulanan, PDRBPengeluaranLajuQtoQ, PDRBPengeluaranLajuYtoY, PDRBPengeluaranLajuCtoC, PDRBLapanganUsahaADHB, PDRBLapanganUsahaADHK, PDRBLapanganUsahaDistribusi, PDRBLapanganUsahaLajuPDRB, PDRBLapanganUsahaLajuImplisit, PDRBLapanganUsahaADHBTriwulanan, PDRBLapanganUsahaADHKTriwulanan, PDRBLapanganUsahaDistribusiTriwulanan, PDRBLapanganUsahaLajuQtoQ, PDRBLapanganUsahaLajuYtoY, PDRBLapanganUsahaLajuCtoC, Inflasi, InflasiPerKomoditas, Bookmark

# Register your models here.

@admin.register(User)
class UserAdmin(BaseUserAdmin):
    list_display = ('id', 'username', 'email', 'first_name', 'last_name', 'is_staff', 'is_active', 'date_joined', 'last_login')
    list_filter = ('is_staff', 'is_superuser', 'is_active', 'date_joined')
    search_fields = ('username', 'email', 'first_name', 'last_name')
    ordering = ('-date_joined',)
    readonly_fields = ('date_joined', 'last_login')
admin.site.register(News)
admin.site.register(Infographic)
admin.site.register(Publication)
admin.site.register(Bookmark)
admin.site.register(Data)
admin.site.register(HumanDevelopmentIndex)
admin.site.register(HotelOccupancyCombined)
admin.site.register(HotelOccupancyYearly)
admin.site.register(GiniRatio)
admin.site.register(IPM_UHH_SP)
admin.site.register(IPM_HLS)
admin.site.register(IPM_RLS)
admin.site.register(IPM_PengeluaranPerKapita)
admin.site.register(IPM_IndeksKesehatan)
admin.site.register(IPM_IndeksHidupLayak)
admin.site.register(IPM_IndeksPendidikan)
admin.site.register(KetenagakerjaanTPT)
admin.site.register(KetenagakerjaanTPAK)
admin.site.register(KemiskinanSurabaya)
admin.site.register(KemiskinanJawaTimur)
admin.site.register(Kependudukan)
admin.site.register(PDRBPengeluaranADHB)
admin.site.register(PDRBPengeluaranADHK)
admin.site.register(PDRBPengeluaranDistribusi)
admin.site.register(PDRBPengeluaranLajuPDRB)
admin.site.register(PDRBPengeluaranADHBTriwulanan)
admin.site.register(PDRBPengeluaranADHKTriwulanan)
admin.site.register(PDRBPengeluaranDistribusiTriwulanan)
admin.site.register(PDRBPengeluaranLajuQtoQ)
admin.site.register(PDRBPengeluaranLajuYtoY)
admin.site.register(PDRBPengeluaranLajuCtoC)
admin.site.register(PDRBLapanganUsahaADHB)
admin.site.register(PDRBLapanganUsahaADHK)
admin.site.register(PDRBLapanganUsahaDistribusi)
admin.site.register(PDRBLapanganUsahaLajuPDRB)
admin.site.register(PDRBLapanganUsahaLajuImplisit)
admin.site.register(PDRBLapanganUsahaADHBTriwulanan)
admin.site.register(PDRBLapanganUsahaADHKTriwulanan)
admin.site.register(PDRBLapanganUsahaDistribusiTriwulanan)
admin.site.register(PDRBLapanganUsahaLajuQtoQ)
admin.site.register(PDRBLapanganUsahaLajuYtoY)
admin.site.register(PDRBLapanganUsahaLajuCtoC)
admin.site.register(Inflasi)
admin.site.register(InflasiPerKomoditas)