# Generated by Django 5.2.8 on 2025-11-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanDevelopmentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('REG', 'Kabupaten/Regency'), ('MUN', 'Kota/Municipality')], default='REG', max_length=3)),
                ('year', models.PositiveIntegerField()),
                ('ipm_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Human Development Index (IPM)',
                'verbose_name_plural': 'Human Development Indices (IPM)',
                'unique_together': {('location_name', 'year')},
            },
        ),
    ]
