# Generated by Django 5.2.7 on 2025-12-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_humandevelopmentindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelOccupancyYearly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Tahun')),
                ('mktj', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='MKTJ')),
                ('tpk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TPK')),
                ('rlmta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='RLMTA')),
                ('rlmtnus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='RLMTNUS')),
                ('rlmtgab', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='RLMTGAB')),
                ('gpr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GPR')),
            ],
            options={
                'verbose_name': 'Tingkat Hunian Hotel (Year-to-Year)',
                'verbose_name_plural': 'Tingkat Hunian Hotel (Year-to-Year)',
            },
        ),
        migrations.AlterModelOptions(
            name='humandevelopmentindex',
            options={'verbose_name': 'Indeks Pembangunan Manusia', 'verbose_name_plural': 'Indeks Pembangunan Manusia'},
        ),
        migrations.AlterField(
            model_name='humandevelopmentindex',
            name='ipm_value',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nilai IPM'),
        ),
        migrations.AlterField(
            model_name='humandevelopmentindex',
            name='location_name',
            field=models.CharField(max_length=255, verbose_name='Nama Lokasi'),
        ),
        migrations.AlterField(
            model_name='humandevelopmentindex',
            name='location_type',
            field=models.CharField(choices=[('REGENCY', 'Kabupaten'), ('MUNICIPALITY', 'Kota')], max_length=20, verbose_name='Tipe Lokasi'),
        ),
        migrations.AlterField(
            model_name='humandevelopmentindex',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Tahun'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='HotelOccupancyCombined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('month', models.CharField(max_length=20, verbose_name='Bulan')),
                ('mktj', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='MKTJ')),
                ('tpk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TPK')),
                ('rlmta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='RLMTA')),
                ('rlmtnus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='RLMTNUS')),
                ('rlmtgab', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='RLMTGAB')),
                ('gpr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='GPR')),
            ],
            options={
                'verbose_name': 'Tingkat Hunian Hotel (Gabung Semua)',
                'verbose_name_plural': 'Tingkat Hunian Hotel (Gabung Semua)',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
