# Generated by Django 5.0.7 on 2025-12-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_hoteloccupancyyearly_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiniRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, verbose_name='Nama Lokasi')),
                ('location_type', models.CharField(choices=[('REGENCY', 'Kabupaten'), ('MUNICIPALITY', 'Kota')], max_length=20, verbose_name='Tipe Lokasi')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('gini_ratio_value', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Nilai Gini Ratio')),
            ],
            options={
                'verbose_name': 'Gini Ratio',
                'verbose_name_plural': 'Gini Ratio',
                'unique_together': {('location_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IPM_HLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, verbose_name='Nama Lokasi')),
                ('location_type', models.CharField(choices=[('REGENCY', 'Kabupaten'), ('MUNICIPALITY', 'Kota')], max_length=20, verbose_name='Tipe Lokasi')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nilai HLS')),
            ],
            options={
                'verbose_name': 'IPM Harapan Lama Sekolah',
                'verbose_name_plural': 'IPM Harapan Lama Sekolah',
                'unique_together': {('location_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IPM_IndeksHidupLayak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, verbose_name='Nama Lokasi')),
                ('location_type', models.CharField(choices=[('REGENCY', 'Kabupaten'), ('MUNICIPALITY', 'Kota')], max_length=20, verbose_name='Tipe Lokasi')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nilai Indeks Hidup Layak')),
            ],
            options={
                'verbose_name': 'IPM Indeks Hidup Layak',
                'verbose_name_plural': 'IPM Indeks Hidup Layak',
                'unique_together': {('location_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IPM_IndeksKesehatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, verbose_name='Nama Lokasi')),
                ('location_type', models.CharField(choices=[('REGENCY', 'Kabupaten'), ('MUNICIPALITY', 'Kota')], max_length=20, verbose_name='Tipe Lokasi')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nilai Indeks Kesehatan')),
            ],
            options={
                'verbose_name': 'IPM Indeks Kesehatan',
                'verbose_name_plural': 'IPM Indeks Kesehatan',
                'unique_together': {('location_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IPM_IndeksPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, verbose_name='Nama Lokasi')),
                ('location_type', models.CharField(choices=[('REGENCY', 'Kabupaten'), ('MUNICIPALITY', 'Kota')], max_length=20, verbose_name='Tipe Lokasi')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nilai Indeks Pendidikan')),
            ],
            options={
                'verbose_name': 'IPM Indeks Pendidikan',
                'verbose_name_plural': 'IPM Indeks Pendidikan',
                'unique_together': {('location_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IPM_PengeluaranPerKapita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, verbose_name='Nama Lokasi')),
                ('location_type', models.CharField(choices=[('REGENCY', 'Kabupaten'), ('MUNICIPALITY', 'Kota')], max_length=20, verbose_name='Tipe Lokasi')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nilai Pengeluaran per Kapita')),
            ],
            options={
                'verbose_name': 'IPM Pengeluaran per Kapita',
                'verbose_name_plural': 'IPM Pengeluaran per Kapita',
                'unique_together': {('location_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IPM_RLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, verbose_name='Nama Lokasi')),
                ('location_type', models.CharField(choices=[('REGENCY', 'Kabupaten'), ('MUNICIPALITY', 'Kota')], max_length=20, verbose_name='Tipe Lokasi')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nilai RLS')),
            ],
            options={
                'verbose_name': 'IPM Rata-rata Lama Sekolah',
                'verbose_name_plural': 'IPM Rata-rata Lama Sekolah',
                'unique_together': {('location_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IPM_UHH_SP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, verbose_name='Nama Lokasi')),
                ('location_type', models.CharField(choices=[('REGENCY', 'Kabupaten'), ('MUNICIPALITY', 'Kota')], max_length=20, verbose_name='Tipe Lokasi')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nilai UHH SP')),
            ],
            options={
                'verbose_name': 'IPM Usia Harapan Hidup saat Lahir (SP)',
                'verbose_name_plural': 'IPM Usia Harapan Hidup saat Lahir (SP)',
                'unique_together': {('location_name', 'year')},
            },
        ),
    ]
