# Generated by Django 5.0.7 on 2025-12-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_giniratio_ipm_hls_ipm_indekshiduplayak_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KemiskinanJawaTimur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Tahun')),
                ('jumlah_penduduk_miskin', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Jumlah Penduduk Miskin (dalam 000)')),
                ('persentase_penduduk_miskin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Persentase Penduduk Miskin')),
                ('indeks_kedalaman_kemiskinan_p1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Indeks Kedalaman Kemiskinan (P1)')),
                ('indeks_keparahan_kemiskinan_p2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Indeks Keparahan Kemiskinan (P2)')),
                ('garis_kemiskinan', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Garis Kemiskinan (Rp/Kapita/Bulan)')),
            ],
            options={
                'verbose_name': 'Kemiskinan Jawa Timur',
                'verbose_name_plural': 'Kemiskinan Jawa Timur',
            },
        ),
        migrations.CreateModel(
            name='KemiskinanSurabaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Tahun')),
                ('jumlah_penduduk_miskin', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Jumlah Penduduk Miskin (dalam 000)')),
                ('persentase_penduduk_miskin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Persentase Penduduk Miskin')),
                ('indeks_kedalaman_kemiskinan_p1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Indeks Kedalaman Kemiskinan (P1)')),
                ('indeks_keparahan_kemiskinan_p2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Indeks Keparahan Kemiskinan (P2)')),
                ('garis_kemiskinan', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Garis Kemiskinan (Rp/Kapita/Bulan)')),
            ],
            options={
                'verbose_name': 'Kemiskinan Surabaya',
                'verbose_name_plural': 'Kemiskinan Surabaya',
            },
        ),
    ]
