# Generated by Django 5.0.7 on 2025-12-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_kemiskinanjawatimur_kemiskinansurabaya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kependudukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=20, verbose_name='Kelompok Umur')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('gender', models.CharField(choices=[('LK', 'Laki-Laki'), ('PR', 'Perempuan'), ('TOTAL', 'Total')], max_length=10, verbose_name='Jenis Kelamin')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Penduduk')),
            ],
            options={
                'verbose_name': 'Kependudukan',
                'verbose_name_plural': 'Kependudukan',
                'unique_together': {('age_group', 'year', 'gender')},
            },
        ),
    ]
