# Generated by Django 5.0.7 on 2025-12-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_kependudukan'),
    ]

    operations = [
        migrations.CreateModel(
            name='KetenagakerjaanTPAK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Tahun')),
                ('laki_laki', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Laki-Laki')),
                ('perempuan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perempuan')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Ketenagakerjaan TPAK',
                'verbose_name_plural': 'Ketenagakerjaan TPAK',
            },
        ),
        migrations.CreateModel(
            name='KetenagakerjaanTPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True, verbose_name='Tahun')),
                ('laki_laki', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Laki-Laki')),
                ('perempuan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perempuan')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Ketenagakerjaan TPT',
                'verbose_name_plural': 'Ketenagakerjaan TPT',
            },
        ),
    ]
