# Generated by Django 5.0.7 on 2025-12-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_ketenagakerjaantpak_ketenagakerjaantpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDRBPengeluaranADHB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_category', models.CharField(max_length=255, verbose_name='Jenis Pengeluaran')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nilai')),
            ],
            options={
                'verbose_name': 'PDRB Pengeluaran ADHB',
                'verbose_name_plural': 'PDRB Pengeluaran ADHB',
                'unique_together': {('expenditure_category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PDRBPengeluaranADHBTriwulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_category', models.CharField(max_length=255, verbose_name='Jenis Pengeluaran')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nilai')),
            ],
            options={
                'verbose_name': 'PDRB Pengeluaran ADHB Triwulanan',
                'verbose_name_plural': 'PDRB Pengeluaran ADHB Triwulanan',
                'unique_together': {('expenditure_category', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='PDRBPengeluaranADHK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_category', models.CharField(max_length=255, verbose_name='Jenis Pengeluaran')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nilai')),
            ],
            options={
                'verbose_name': 'PDRB Pengeluaran ADHK',
                'verbose_name_plural': 'PDRB Pengeluaran ADHK',
                'unique_together': {('expenditure_category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PDRBPengeluaranADHKTriwulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_category', models.CharField(max_length=255, verbose_name='Jenis Pengeluaran')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nilai')),
            ],
            options={
                'verbose_name': 'PDRB Pengeluaran ADHK Triwulanan',
                'verbose_name_plural': 'PDRB Pengeluaran ADHK Triwulanan',
                'unique_together': {('expenditure_category', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='PDRBPengeluaranDistribusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_category', models.CharField(max_length=255, verbose_name='Jenis Pengeluaran')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nilai (%)')),
            ],
            options={
                'verbose_name': 'PDRB Pengeluaran Distribusi',
                'verbose_name_plural': 'PDRB Pengeluaran Distribusi',
                'unique_together': {('expenditure_category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PDRBPengeluaranDistribusiTriwulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_category', models.CharField(max_length=255, verbose_name='Jenis Pengeluaran')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nilai (%)')),
            ],
            options={
                'verbose_name': 'PDRB Pengeluaran Distribusi Triwulanan',
                'verbose_name_plural': 'PDRB Pengeluaran Distribusi Triwulanan',
                'unique_together': {('expenditure_category', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='PDRBPengeluaranLajuCtoC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_category', models.CharField(max_length=255, verbose_name='Jenis Pengeluaran')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Laju Pertumbuhan C-to-C (%)')),
            ],
            options={
                'verbose_name': 'PDRB Pengeluaran Laju C-to-C',
                'verbose_name_plural': 'PDRB Pengeluaran Laju C-to-C',
                'unique_together': {('expenditure_category', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='PDRBPengeluaranLajuPDRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_category', models.CharField(max_length=255, verbose_name='Jenis Pengeluaran')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Laju Pertumbuhan (%)')),
            ],
            options={
                'verbose_name': 'PDRB Pengeluaran Laju PDRB',
                'verbose_name_plural': 'PDRB Pengeluaran Laju PDRB',
                'unique_together': {('expenditure_category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PDRBPengeluaranLajuQtoQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_category', models.CharField(max_length=255, verbose_name='Jenis Pengeluaran')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Laju Pertumbuhan Q-to-Q (%)')),
            ],
            options={
                'verbose_name': 'PDRB Pengeluaran Laju Q-to-Q',
                'verbose_name_plural': 'PDRB Pengeluaran Laju Q-to-Q',
                'unique_together': {('expenditure_category', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='PDRBPengeluaranLajuYtoY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_category', models.CharField(max_length=255, verbose_name='Jenis Pengeluaran')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Laju Pertumbuhan Y-to-Y (%)')),
            ],
            options={
                'verbose_name': 'PDRB Pengeluaran Laju Y-to-Y',
                'verbose_name_plural': 'PDRB Pengeluaran Laju Y-to-Y',
                'unique_together': {('expenditure_category', 'year', 'quarter')},
            },
        ),
    ]
