# Generated by Django 5.0.7 on 2025-12-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_pdrbpengeluaranadhb_pdrbpengeluaranadhbtriwulanan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDRBLapanganUsahaADHB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=255, verbose_name='Lapangan Usaha')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nilai')),
            ],
            options={
                'verbose_name': 'PDRB Lapangan Usaha ADHB',
                'verbose_name_plural': 'PDRB Lapangan Usaha ADHB',
                'unique_together': {('industry_category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PDRBLapanganUsahaADHBTriwulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=255, verbose_name='Lapangan Usaha')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nilai')),
            ],
            options={
                'verbose_name': 'PDRB Lapangan Usaha ADHB Triwulanan',
                'verbose_name_plural': 'PDRB Lapangan Usaha ADHB Triwulanan',
                'unique_together': {('industry_category', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='PDRBLapanganUsahaADHK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=255, verbose_name='Lapangan Usaha')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nilai')),
            ],
            options={
                'verbose_name': 'PDRB Lapangan Usaha ADHK',
                'verbose_name_plural': 'PDRB Lapangan Usaha ADHK',
                'unique_together': {('industry_category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PDRBLapanganUsahaADHKTriwulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=255, verbose_name='Lapangan Usaha')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Nilai')),
            ],
            options={
                'verbose_name': 'PDRB Lapangan Usaha ADHK Triwulanan',
                'verbose_name_plural': 'PDRB Lapangan Usaha ADHK Triwulanan',
                'unique_together': {('industry_category', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='PDRBLapanganUsahaDistribusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=255, verbose_name='Lapangan Usaha')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nilai (%)')),
            ],
            options={
                'verbose_name': 'PDRB Lapangan Usaha Distribusi',
                'verbose_name_plural': 'PDRB Lapangan Usaha Distribusi',
                'unique_together': {('industry_category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PDRBLapanganUsahaDistribusiTriwulanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=255, verbose_name='Lapangan Usaha')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nilai (%)')),
            ],
            options={
                'verbose_name': 'PDRB Lapangan Usaha Distribusi Triwulanan',
                'verbose_name_plural': 'PDRB Lapangan Usaha Distribusi Triwulanan',
                'unique_together': {('industry_category', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='PDRBLapanganUsahaLajuCtoC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=255, verbose_name='Lapangan Usaha')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Laju Pertumbuhan C-to-C (%)')),
            ],
            options={
                'verbose_name': 'PDRB Lapangan Usaha Laju C-to-C',
                'verbose_name_plural': 'PDRB Lapangan Usaha Laju C-to-C',
                'unique_together': {('industry_category', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='PDRBLapanganUsahaLajuImplisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=255, verbose_name='Lapangan Usaha')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Laju Implisit (%)')),
            ],
            options={
                'verbose_name': 'PDRB Lapangan Usaha Laju Implisit',
                'verbose_name_plural': 'PDRB Lapangan Usaha Laju Implisit',
                'unique_together': {('industry_category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PDRBLapanganUsahaLajuPDRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=255, verbose_name='Lapangan Usaha')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Laju Pertumbuhan (%)')),
            ],
            options={
                'verbose_name': 'PDRB Lapangan Usaha Laju PDRB',
                'verbose_name_plural': 'PDRB Lapangan Usaha Laju PDRB',
                'unique_together': {('industry_category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PDRBLapanganUsahaLajuQtoQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=255, verbose_name='Lapangan Usaha')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Laju Pertumbuhan Q-to-Q (%)')),
            ],
            options={
                'verbose_name': 'PDRB Lapangan Usaha Laju Q-to-Q',
                'verbose_name_plural': 'PDRB Lapangan Usaha Laju Q-to-Q',
                'unique_together': {('industry_category', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='PDRBLapanganUsahaLajuYtoY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_category', models.CharField(max_length=255, verbose_name='Lapangan Usaha')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('quarter', models.CharField(choices=[('I', 'Triwulan I'), ('II', 'Triwulan II'), ('III', 'Triwulan III'), ('IV', 'Triwulan IV'), ('TOTAL', 'Jumlah/Total')], max_length=5, verbose_name='Triwulan')),
                ('preliminary_flag', models.CharField(blank=True, choices=[('', 'Final'), ('*', 'Preliminary'), ('**', 'Very Preliminary'), ('***', 'Very Very Preliminary')], default='', max_length=3, verbose_name='Status Data')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Laju Pertumbuhan Y-to-Y (%)')),
            ],
            options={
                'verbose_name': 'PDRB Lapangan Usaha Laju Y-to-Y',
                'verbose_name_plural': 'PDRB Lapangan Usaha Laju Y-to-Y',
                'unique_together': {('industry_category', 'year', 'quarter')},
            },
        ),
    ]
