# Generated by Django 5.0.7 on 2025-12-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_pdrblapanganusahaadhb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infographic',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='infographic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='infographic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
