# Generated by Django 5.2.7 on 2025-12-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_infographic_options_infographic_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infographic',
            options={},
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_id',
            field=models.CharField(unique=True),
        ),
        migrations.CreateModel(
            name='Inflasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('month', models.CharField(choices=[('JANUARI', 'Januari'), ('FEBRUARI', 'Februari'), ('MARET', 'Maret'), ('APRIL', 'April'), ('MEI', 'Mei'), ('JUNI', 'Juni'), ('JULI', 'Juli'), ('AGUSTUS', 'Agustus'), ('SEPTEMBER', 'September'), ('OKTOBER', 'Oktober'), ('NOPEMBER', 'November'), ('DESEMBER', 'Desember')], max_length=20, verbose_name='Bulan')),
                ('bulanan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bulanan (%)')),
                ('kumulatif', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kumulatif (%)')),
                ('yoy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='YoY (%)')),
            ],
            options={
                'verbose_name': 'Inflasi',
                'verbose_name_plural': 'Inflasi',
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='InflasiPerKomoditas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_code', models.CharField(max_length=50, verbose_name='Kode Komoditas')),
                ('commodity_name', models.CharField(max_length=255, verbose_name='Nama Komoditas')),
                ('flag', models.CharField(blank=True, max_length=10, null=True, verbose_name='Flag')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Tahun')),
                ('month', models.CharField(choices=[('JANUARI', 'Januari'), ('FEBRUARI', 'Februari'), ('MARET', 'Maret'), ('APRIL', 'April'), ('MEI', 'Mei'), ('JUNI', 'Juni'), ('JULI', 'Juli'), ('AGUSTUS', 'Agustus'), ('SEPTEMBER', 'September'), ('OKTOBER', 'Oktober'), ('NOPEMBER', 'November'), ('DESEMBER', 'Desember')], max_length=20, verbose_name='Bulan')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nilai (%)')),
            ],
            options={
                'verbose_name': 'Inflasi Per Komoditas',
                'verbose_name_plural': 'Inflasi Per Komoditas',
                'indexes': [models.Index(fields=['commodity_code', 'year'], name='apps_inflas_commodi_5667a0_idx'), models.Index(fields=['year', 'month'], name='apps_inflas_year_54e64c_idx')],
                'unique_together': {('commodity_code', 'year', 'month')},
            },
        ),
    ]
