# Generated by Django 5.2.7 on 2025-12-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_infographic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infographic',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='infographic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='infographic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='inflasiperkomoditas',
            unique_together={('commodity_code', 'flag', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='inflasiperkomoditas',
            index=models.Index(fields=['commodity_code', 'flag', 'year'], name='apps_inflas_commodi_529319_idx'),
        ),
    ]
